### ISSUE TITLE
Data is missing

### ISSUE THREAD

**Issue by jamesmkrieger** [flatironinstitute/Ensemble-reweighting-using-Cryo-EM-particles#1]
The examples rely on a data directory, which isn't available in this repository.

It would be especially useful to know what rot_mats_struc_image.npy contains. Structures, simulations and images can hopefully be replaced by those from elsewhere fairly easily, but the matrices npy is harder to reproduce without information.

**Comment by bob-carpenter** [comment]
@ehthiede @picossio : 

Do we have permission to redistribute the data?  

If not, is there a way to point people to it so they can download it directly?  

If so, will it fit on GitHub?  If it doesn't fit on GitHub, we can distribute larger files through Flatiron's compute.

**Comment by picossio** [comment]
@wstangfi can make this available.

**Comment by wstangfi** [comment]
Just added example data files in the "data" folders along with some example useful scripts for calculating the rotation matrix (tools/calc_rot_mats.py) and analyzing the results

**Comment by jamesmkrieger** [comment]
Thanks very much
